name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: ls
    - run: cd "docker"
    - run: ls
    - run: cd "production"
    - run: ls
    - name: Build the Docker image
      run:  docker-compose up -d
